name: django-backend

services: 

  db:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'django-backend'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build:
    restart: unless-stopped
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      CORE_SETTING_DATABASE: '{ "default": { "HOST": "db" }  }'
      CORE_SETTING_LOCAL_SETTINGS_PATH: 'local/settings.prod.py'

volumes:
  postgresql-data:
    driver: local