name: django-backend

services: 

  db:
    image: postgres:16.3-alpine3.20
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'django-backend'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
    driver: local